// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/types/types.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	pkg/types/types.proto

It has these top-level messages:
	Workflow
	WorkflowSpec
	WorkflowStatus
	WorkflowInvocation
	WorkflowInvocationSpec
	WorkflowInvocationStatus
	DependencyConfig
	Task
	TaskSpec
	TaskStatus
	TaskDependencyParameters
	TaskRun
	TaskRunSpec
	TaskRunStatus
	ObjectMetadata
	TypedValue
	Error
	FnRef
	TypedValueMap
	TypedValueList
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorkflowStatus_Status int32

const (
	WorkflowStatus_PENDING WorkflowStatus_Status = 0
	//        PARSING = 1; // During validation/parsing
	WorkflowStatus_READY   WorkflowStatus_Status = 2
	WorkflowStatus_FAILED  WorkflowStatus_Status = 3
	WorkflowStatus_DELETED WorkflowStatus_Status = 4
)

var WorkflowStatus_Status_name = map[int32]string{
	0: "PENDING",
	2: "READY",
	3: "FAILED",
	4: "DELETED",
}
var WorkflowStatus_Status_value = map[string]int32{
	"PENDING": 0,
	"READY":   2,
	"FAILED":  3,
	"DELETED": 4,
}

func (x WorkflowStatus_Status) String() string {
	return proto.EnumName(WorkflowStatus_Status_name, int32(x))
}
func (WorkflowStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type WorkflowInvocationStatus_Status int32

const (
	WorkflowInvocationStatus_UNKNOWN     WorkflowInvocationStatus_Status = 0
	WorkflowInvocationStatus_SCHEDULED   WorkflowInvocationStatus_Status = 1
	WorkflowInvocationStatus_IN_PROGRESS WorkflowInvocationStatus_Status = 2
	WorkflowInvocationStatus_SUCCEEDED   WorkflowInvocationStatus_Status = 3
	WorkflowInvocationStatus_FAILED      WorkflowInvocationStatus_Status = 4
	WorkflowInvocationStatus_ABORTED     WorkflowInvocationStatus_Status = 5
)

var WorkflowInvocationStatus_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SCHEDULED",
	2: "IN_PROGRESS",
	3: "SUCCEEDED",
	4: "FAILED",
	5: "ABORTED",
}
var WorkflowInvocationStatus_Status_value = map[string]int32{
	"UNKNOWN":     0,
	"SCHEDULED":   1,
	"IN_PROGRESS": 2,
	"SUCCEEDED":   3,
	"FAILED":      4,
	"ABORTED":     5,
}

func (x WorkflowInvocationStatus_Status) String() string {
	return proto.EnumName(WorkflowInvocationStatus_Status_name, int32(x))
}
func (WorkflowInvocationStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type TaskStatus_Status int32

const (
	TaskStatus_STARTED TaskStatus_Status = 0
	TaskStatus_READY   TaskStatus_Status = 1
	TaskStatus_FAILED  TaskStatus_Status = 2
)

var TaskStatus_Status_name = map[int32]string{
	0: "STARTED",
	1: "READY",
	2: "FAILED",
}
var TaskStatus_Status_value = map[string]int32{
	"STARTED": 0,
	"READY":   1,
	"FAILED":  2,
}

func (x TaskStatus_Status) String() string {
	return proto.EnumName(TaskStatus_Status_name, int32(x))
}
func (TaskStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

type TaskDependencyParameters_DependencyType int32

const (
	TaskDependencyParameters_DATA           TaskDependencyParameters_DependencyType = 0
	TaskDependencyParameters_CONTROL        TaskDependencyParameters_DependencyType = 1
	TaskDependencyParameters_DYNAMIC_OUTPUT TaskDependencyParameters_DependencyType = 2
)

var TaskDependencyParameters_DependencyType_name = map[int32]string{
	0: "DATA",
	1: "CONTROL",
	2: "DYNAMIC_OUTPUT",
}
var TaskDependencyParameters_DependencyType_value = map[string]int32{
	"DATA":           0,
	"CONTROL":        1,
	"DYNAMIC_OUTPUT": 2,
}

func (x TaskDependencyParameters_DependencyType) String() string {
	return proto.EnumName(TaskDependencyParameters_DependencyType_name, int32(x))
}
func (TaskDependencyParameters_DependencyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

type TaskRunStatus_Status int32

const (
	TaskRunStatus_UNKNOWN     TaskRunStatus_Status = 0
	TaskRunStatus_SCHEDULED   TaskRunStatus_Status = 1
	TaskRunStatus_IN_PROGRESS TaskRunStatus_Status = 2
	TaskRunStatus_SUCCEEDED   TaskRunStatus_Status = 3
	TaskRunStatus_FAILED      TaskRunStatus_Status = 4
	TaskRunStatus_ABORTED     TaskRunStatus_Status = 5
	TaskRunStatus_SKIPPED     TaskRunStatus_Status = 6
)

var TaskRunStatus_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SCHEDULED",
	2: "IN_PROGRESS",
	3: "SUCCEEDED",
	4: "FAILED",
	5: "ABORTED",
	6: "SKIPPED",
}
var TaskRunStatus_Status_value = map[string]int32{
	"UNKNOWN":     0,
	"SCHEDULED":   1,
	"IN_PROGRESS": 2,
	"SUCCEEDED":   3,
	"FAILED":      4,
	"ABORTED":     5,
	"SKIPPED":     6,
}

func (x TaskRunStatus_Status) String() string {
	return proto.EnumName(TaskRunStatus_Status_name, int32(x))
}
func (TaskRunStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{13, 0} }

//
// Workflow Model
//
type Workflow struct {
	Metadata *ObjectMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *WorkflowSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status   *WorkflowStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Workflow) Reset()                    { *m = Workflow{} }
func (m *Workflow) String() string            { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()               {}
func (*Workflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Workflow) GetMetadata() *ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Workflow) GetSpec() *WorkflowSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Workflow) GetStatus() *WorkflowStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Workflow Definition
//
// The workflowDefinition contains the definition of a workflow.
//
// Ideally the source code (json, yaml) can be converted directly to this message.
// Naming, triggers and versioning of the workflow itself is out of the scope of this data structure, which is delegated
// to the user/system upon the creation of a workflow.
type WorkflowSpec struct {
	// apiVersion describes what version is of the workflow definition.
	// By default the workflow engine will assume the latest version to be used.
	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion" json:"apiVersion,omitempty"`
	// Tasks contains the specs of the tasks, with the key being the task id.
	//
	// Note: Dependency graph is build into the tasks.
	Tasks map[string]*TaskSpec `protobuf:"bytes,2,rep,name=tasks" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// From which task should the workflow return the output? Future: multiple? Implicit?
	OutputTask  string `protobuf:"bytes,3,opt,name=outputTask" json:"outputTask,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	// The UID that the workflow should have. Only use this in case you want to force a specific UID.
	ForceId string `protobuf:"bytes,5,opt,name=forceId" json:"forceId,omitempty"`
	// Name is solely for human-readablity
	Name string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	// Internal indicates whether is a workflow should be visible to a human (default) or not.
	//
	Internal bool `protobuf:"varint,7,opt,name=internal" json:"internal,omitempty"`
}

func (m *WorkflowSpec) Reset()                    { *m = WorkflowSpec{} }
func (m *WorkflowSpec) String() string            { return proto.CompactTextString(m) }
func (*WorkflowSpec) ProtoMessage()               {}
func (*WorkflowSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WorkflowSpec) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *WorkflowSpec) GetTasks() map[string]*TaskSpec {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *WorkflowSpec) GetOutputTask() string {
	if m != nil {
		return m.OutputTask
	}
	return ""
}

func (m *WorkflowSpec) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *WorkflowSpec) GetForceId() string {
	if m != nil {
		return m.ForceId
	}
	return ""
}

func (m *WorkflowSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowSpec) GetInternal() bool {
	if m != nil {
		return m.Internal
	}
	return false
}

type WorkflowStatus struct {
	Status    WorkflowStatus_Status      `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.WorkflowStatus_Status" json:"status,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=updatedAt" json:"updatedAt,omitempty"`
	// Tasks contains the status of the tasks, with the key being the task id.
	Tasks map[string]*TaskStatus `protobuf:"bytes,3,rep,name=tasks" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error *Error                 `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *WorkflowStatus) Reset()                    { *m = WorkflowStatus{} }
func (m *WorkflowStatus) String() string            { return proto.CompactTextString(m) }
func (*WorkflowStatus) ProtoMessage()               {}
func (*WorkflowStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WorkflowStatus) GetStatus() WorkflowStatus_Status {
	if m != nil {
		return m.Status
	}
	return WorkflowStatus_PENDING
}

func (m *WorkflowStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *WorkflowStatus) GetTasks() map[string]*TaskStatus {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *WorkflowStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

//
// Workflow Invocation Model
//
type WorkflowInvocation struct {
	Metadata *ObjectMetadata           `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *WorkflowInvocationSpec   `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status   *WorkflowInvocationStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *WorkflowInvocation) Reset()                    { *m = WorkflowInvocation{} }
func (m *WorkflowInvocation) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocation) ProtoMessage()               {}
func (*WorkflowInvocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WorkflowInvocation) GetMetadata() *ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WorkflowInvocation) GetSpec() *WorkflowInvocationSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *WorkflowInvocation) GetStatus() *WorkflowInvocationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Workflow Invocation Model
type WorkflowInvocationSpec struct {
	WorkflowId string                 `protobuf:"bytes,1,opt,name=workflowId" json:"workflowId,omitempty"`
	Inputs     map[string]*TypedValue `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ParentId contains the id of the encapsulating workflow invocation.
	//
	// This used within the workflow engine; for user-provided workflow invocations the parentId is ignored.
	ParentId string `protobuf:"bytes,3,opt,name=parentId" json:"parentId,omitempty"`
}

func (m *WorkflowInvocationSpec) Reset()                    { *m = WorkflowInvocationSpec{} }
func (m *WorkflowInvocationSpec) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocationSpec) ProtoMessage()               {}
func (*WorkflowInvocationSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WorkflowInvocationSpec) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *WorkflowInvocationSpec) GetInputs() map[string]*TypedValue {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *WorkflowInvocationSpec) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

type WorkflowInvocationStatus struct {
	Status    WorkflowInvocationStatus_Status `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.WorkflowInvocationStatus_Status" json:"status,omitempty"`
	UpdatedAt *google_protobuf.Timestamp      `protobuf:"bytes,2,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Tasks     map[string]*TaskRun             `protobuf:"bytes,3,rep,name=tasks" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Output    *TypedValue                     `protobuf:"bytes,4,opt,name=output" json:"output,omitempty"`
	// In case the task ID also exists in the workflow spec, the dynamic task will be
	// used as an overlay over the static task.
	DynamicTasks map[string]*Task `protobuf:"bytes,5,rep,name=dynamicTasks" json:"dynamicTasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error        *Error           `protobuf:"bytes,6,opt,name=error" json:"error,omitempty"`
}

func (m *WorkflowInvocationStatus) Reset()                    { *m = WorkflowInvocationStatus{} }
func (m *WorkflowInvocationStatus) String() string            { return proto.CompactTextString(m) }
func (*WorkflowInvocationStatus) ProtoMessage()               {}
func (*WorkflowInvocationStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WorkflowInvocationStatus) GetStatus() WorkflowInvocationStatus_Status {
	if m != nil {
		return m.Status
	}
	return WorkflowInvocationStatus_UNKNOWN
}

func (m *WorkflowInvocationStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetTasks() map[string]*TaskRun {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetOutput() *TypedValue {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetDynamicTasks() map[string]*Task {
	if m != nil {
		return m.DynamicTasks
	}
	return nil
}

func (m *WorkflowInvocationStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DependencyConfig struct {
	// Dependencies for this task to execute
	Requires map[string]*TaskDependencyParameters `protobuf:"bytes,1,rep,name=requires" json:"requires,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Number of dependencies to wait for
	Await int32 `protobuf:"varint,2,opt,name=await" json:"await,omitempty"`
}

func (m *DependencyConfig) Reset()                    { *m = DependencyConfig{} }
func (m *DependencyConfig) String() string            { return proto.CompactTextString(m) }
func (*DependencyConfig) ProtoMessage()               {}
func (*DependencyConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DependencyConfig) GetRequires() map[string]*TaskDependencyParameters {
	if m != nil {
		return m.Requires
	}
	return nil
}

func (m *DependencyConfig) GetAwait() int32 {
	if m != nil {
		return m.Await
	}
	return 0
}

//
// Task Model
//
type Task struct {
	Metadata *ObjectMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *TaskSpec       `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status   *TaskStatus     `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Task) GetMetadata() *ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Task) GetSpec() *TaskSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Task) GetStatus() *TaskStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// A task is the primitive unit of a workflow, representing an action that needs to be performed in order to continue.
//
// A task as a number of inputs and exactly two outputs
// Id is specified outside of TaskSpec
type TaskSpec struct {
	// Name/identifier of the function
	FunctionRef string                 `protobuf:"bytes,1,opt,name=functionRef" json:"functionRef,omitempty"`
	Inputs      map[string]*TypedValue `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Dependencies for this task to execute
	Requires map[string]*TaskDependencyParameters `protobuf:"bytes,3,rep,name=requires" json:"requires,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Number of dependencies to wait for
	Await int32 `protobuf:"varint,4,opt,name=await" json:"await,omitempty"`
	// Transform the output, or override the output with a literal
	Output *TypedValue `protobuf:"bytes,5,opt,name=output" json:"output,omitempty"`
}

func (m *TaskSpec) Reset()                    { *m = TaskSpec{} }
func (m *TaskSpec) String() string            { return proto.CompactTextString(m) }
func (*TaskSpec) ProtoMessage()               {}
func (*TaskSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TaskSpec) GetFunctionRef() string {
	if m != nil {
		return m.FunctionRef
	}
	return ""
}

func (m *TaskSpec) GetInputs() map[string]*TypedValue {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TaskSpec) GetRequires() map[string]*TaskDependencyParameters {
	if m != nil {
		return m.Requires
	}
	return nil
}

func (m *TaskSpec) GetAwait() int32 {
	if m != nil {
		return m.Await
	}
	return 0
}

func (m *TaskSpec) GetOutput() *TypedValue {
	if m != nil {
		return m.Output
	}
	return nil
}

type TaskStatus struct {
	Status    TaskStatus_Status          `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.TaskStatus_Status" json:"status,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=updatedAt" json:"updatedAt,omitempty"`
	FnRef     *FnRef                     `protobuf:"bytes,3,opt,name=fnRef" json:"fnRef,omitempty"`
	Error     *Error                     `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *TaskStatus) Reset()                    { *m = TaskStatus{} }
func (m *TaskStatus) String() string            { return proto.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()               {}
func (*TaskStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TaskStatus) GetStatus() TaskStatus_Status {
	if m != nil {
		return m.Status
	}
	return TaskStatus_STARTED
}

func (m *TaskStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *TaskStatus) GetFnRef() *FnRef {
	if m != nil {
		return m.FnRef
	}
	return nil
}

func (m *TaskStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TaskDependencyParameters struct {
	Type  TaskDependencyParameters_DependencyType `protobuf:"varint,1,opt,name=type,enum=fission.workflows.types.TaskDependencyParameters_DependencyType" json:"type,omitempty"`
	Alias string                                  `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
}

func (m *TaskDependencyParameters) Reset()                    { *m = TaskDependencyParameters{} }
func (m *TaskDependencyParameters) String() string            { return proto.CompactTextString(m) }
func (*TaskDependencyParameters) ProtoMessage()               {}
func (*TaskDependencyParameters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TaskDependencyParameters) GetType() TaskDependencyParameters_DependencyType {
	if m != nil {
		return m.Type
	}
	return TaskDependencyParameters_DATA
}

func (m *TaskDependencyParameters) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

//
// Task Run Model
//
type TaskRun struct {
	Metadata *ObjectMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Spec     *TaskRunSpec    `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Status   *TaskRunStatus  `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *TaskRun) Reset()                    { *m = TaskRun{} }
func (m *TaskRun) String() string            { return proto.CompactTextString(m) }
func (*TaskRun) ProtoMessage()               {}
func (*TaskRun) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *TaskRun) GetMetadata() *ObjectMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *TaskRun) GetSpec() *TaskRunSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *TaskRun) GetStatus() *TaskRunStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type TaskRunSpec struct {
	// Id of the task to be invoked (no ambiguatity at this point
	FnRef *FnRef `protobuf:"bytes,1,opt,name=fnRef" json:"fnRef,omitempty"`
	// TaskId is the id of the task within the workflow
	TaskId string `protobuf:"bytes,2,opt,name=taskId" json:"taskId,omitempty"`
	// Inputs contain all inputs to the task run
	Inputs map[string]*TypedValue `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	//
	InvocationId string `protobuf:"bytes,4,opt,name=invocationId" json:"invocationId,omitempty"`
}

func (m *TaskRunSpec) Reset()                    { *m = TaskRunSpec{} }
func (m *TaskRunSpec) String() string            { return proto.CompactTextString(m) }
func (*TaskRunSpec) ProtoMessage()               {}
func (*TaskRunSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *TaskRunSpec) GetFnRef() *FnRef {
	if m != nil {
		return m.FnRef
	}
	return nil
}

func (m *TaskRunSpec) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskRunSpec) GetInputs() map[string]*TypedValue {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TaskRunSpec) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

type TaskRunStatus struct {
	Status    TaskRunStatus_Status       `protobuf:"varint,1,opt,name=status,enum=fission.workflows.types.TaskRunStatus_Status" json:"status,omitempty"`
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Output    *TypedValue                `protobuf:"bytes,3,opt,name=output" json:"output,omitempty"`
	Error     *Error                     `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *TaskRunStatus) Reset()                    { *m = TaskRunStatus{} }
func (m *TaskRunStatus) String() string            { return proto.CompactTextString(m) }
func (*TaskRunStatus) ProtoMessage()               {}
func (*TaskRunStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TaskRunStatus) GetStatus() TaskRunStatus_Status {
	if m != nil {
		return m.Status
	}
	return TaskRunStatus_UNKNOWN
}

func (m *TaskRunStatus) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *TaskRunStatus) GetOutput() *TypedValue {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *TaskRunStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

//
// Common
//
type ObjectMetadata struct {
	Id        string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *ObjectMetadata) Reset()                    { *m = ObjectMetadata{} }
func (m *ObjectMetadata) String() string            { return proto.CompactTextString(m) }
func (*ObjectMetadata) ProtoMessage()               {}
func (*ObjectMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ObjectMetadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectMetadata) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// Copy of protobuf's Any, to avoid protobuf requirement of a protobuf-based type.
type TypedValue struct {
	Type   string            `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Value  []byte            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TypedValue) Reset()                    { *m = TypedValue{} }
func (m *TypedValue) String() string            { return proto.CompactTextString(m) }
func (*TypedValue) ProtoMessage()               {}
func (*TypedValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *TypedValue) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TypedValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TypedValue) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Error struct {
	//    string code = 1;
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// FnRef is an immutable, unique reference to a function on a specific function runtime environment.
//
// The string representation (via String or Format): runtime://runtimeId
type FnRef struct {
	// Runtime is the Function Runtime environment (fnenv) that was used to resolve the function.
	Runtime string `protobuf:"bytes,2,opt,name=runtime" json:"runtime,omitempty"`
	// Namespace is the namespace of the fission function.
	Namespace string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	// ID is the runtime-specific identifier of the function.
	ID string `protobuf:"bytes,4,opt,name=ID" json:"ID,omitempty"`
}

func (m *FnRef) Reset()                    { *m = FnRef{} }
func (m *FnRef) String() string            { return proto.CompactTextString(m) }
func (*FnRef) ProtoMessage()               {}
func (*FnRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *FnRef) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *FnRef) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *FnRef) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// Utility wrapper for a TypedValue map
type TypedValueMap struct {
	Value map[string]*TypedValue `protobuf:"bytes,1,rep,name=Value" json:"Value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TypedValueMap) Reset()                    { *m = TypedValueMap{} }
func (m *TypedValueMap) String() string            { return proto.CompactTextString(m) }
func (*TypedValueMap) ProtoMessage()               {}
func (*TypedValueMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *TypedValueMap) GetValue() map[string]*TypedValue {
	if m != nil {
		return m.Value
	}
	return nil
}

// Utility wrapper for a TypedValue list
type TypedValueList struct {
	Value []*TypedValue `protobuf:"bytes,1,rep,name=Value" json:"Value,omitempty"`
}

func (m *TypedValueList) Reset()                    { *m = TypedValueList{} }
func (m *TypedValueList) String() string            { return proto.CompactTextString(m) }
func (*TypedValueList) ProtoMessage()               {}
func (*TypedValueList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *TypedValueList) GetValue() []*TypedValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Workflow)(nil), "fission.workflows.types.Workflow")
	proto.RegisterType((*WorkflowSpec)(nil), "fission.workflows.types.WorkflowSpec")
	proto.RegisterType((*WorkflowStatus)(nil), "fission.workflows.types.WorkflowStatus")
	proto.RegisterType((*WorkflowInvocation)(nil), "fission.workflows.types.WorkflowInvocation")
	proto.RegisterType((*WorkflowInvocationSpec)(nil), "fission.workflows.types.WorkflowInvocationSpec")
	proto.RegisterType((*WorkflowInvocationStatus)(nil), "fission.workflows.types.WorkflowInvocationStatus")
	proto.RegisterType((*DependencyConfig)(nil), "fission.workflows.types.DependencyConfig")
	proto.RegisterType((*Task)(nil), "fission.workflows.types.Task")
	proto.RegisterType((*TaskSpec)(nil), "fission.workflows.types.TaskSpec")
	proto.RegisterType((*TaskStatus)(nil), "fission.workflows.types.TaskStatus")
	proto.RegisterType((*TaskDependencyParameters)(nil), "fission.workflows.types.TaskDependencyParameters")
	proto.RegisterType((*TaskRun)(nil), "fission.workflows.types.TaskRun")
	proto.RegisterType((*TaskRunSpec)(nil), "fission.workflows.types.TaskRunSpec")
	proto.RegisterType((*TaskRunStatus)(nil), "fission.workflows.types.TaskRunStatus")
	proto.RegisterType((*ObjectMetadata)(nil), "fission.workflows.types.ObjectMetadata")
	proto.RegisterType((*TypedValue)(nil), "fission.workflows.types.TypedValue")
	proto.RegisterType((*Error)(nil), "fission.workflows.types.Error")
	proto.RegisterType((*FnRef)(nil), "fission.workflows.types.FnRef")
	proto.RegisterType((*TypedValueMap)(nil), "fission.workflows.types.TypedValueMap")
	proto.RegisterType((*TypedValueList)(nil), "fission.workflows.types.TypedValueList")
	proto.RegisterEnum("fission.workflows.types.WorkflowStatus_Status", WorkflowStatus_Status_name, WorkflowStatus_Status_value)
	proto.RegisterEnum("fission.workflows.types.WorkflowInvocationStatus_Status", WorkflowInvocationStatus_Status_name, WorkflowInvocationStatus_Status_value)
	proto.RegisterEnum("fission.workflows.types.TaskStatus_Status", TaskStatus_Status_name, TaskStatus_Status_value)
	proto.RegisterEnum("fission.workflows.types.TaskDependencyParameters_DependencyType", TaskDependencyParameters_DependencyType_name, TaskDependencyParameters_DependencyType_value)
	proto.RegisterEnum("fission.workflows.types.TaskRunStatus_Status", TaskRunStatus_Status_name, TaskRunStatus_Status_value)
}

func init() { proto.RegisterFile("pkg/types/types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0x0e, 0x29, 0x51, 0x96, 0x8e, 0x6c, 0x5d, 0xdd, 0xc1, 0xbd, 0xa9, 0x20, 0xb4, 0xa9, 0xc3,
	0xfe, 0x05, 0x45, 0x43, 0x37, 0x4e, 0xda, 0xd8, 0x75, 0xd1, 0x56, 0x11, 0x69, 0x87, 0xb0, 0x2d,
	0x09, 0x94, 0x9c, 0x20, 0x29, 0x92, 0x60, 0x2c, 0x8e, 0x0c, 0xc6, 0x12, 0xc5, 0x92, 0x54, 0x02,
	0x3f, 0x42, 0xdf, 0xa3, 0x9b, 0x02, 0xdd, 0x17, 0xe8, 0xa6, 0x8b, 0x6e, 0x0a, 0xf4, 0x21, 0xba,
	0xe8, 0xaa, 0x8b, 0xa2, 0xe8, 0x1b, 0x14, 0x33, 0x1c, 0x8a, 0x43, 0xc5, 0xb2, 0xa4, 0x54, 0xe9,
	0x46, 0xe2, 0x0c, 0xcf, 0x39, 0x73, 0xe6, 0x3b, 0xdf, 0xf9, 0x66, 0x08, 0xff, 0xf7, 0x4e, 0x4f,
	0x36, 0xc2, 0x33, 0x8f, 0x04, 0xd1, 0xaf, 0xe6, 0xf9, 0xc3, 0x70, 0x88, 0x5e, 0xeb, 0x39, 0x41,
	0xe0, 0x0c, 0x5d, 0xed, 0xf9, 0xd0, 0x3f, 0xed, 0xf5, 0x87, 0xcf, 0x03, 0x8d, 0xbd, 0xae, 0xbe,
	0x79, 0x32, 0x1c, 0x9e, 0xf4, 0xc9, 0x06, 0x33, 0x3b, 0x1e, 0xf5, 0x36, 0x42, 0x67, 0x40, 0x82,
	0x10, 0x0f, 0xbc, 0xc8, 0x53, 0xfd, 0x45, 0x82, 0xfc, 0x7d, 0xee, 0x84, 0xea, 0x90, 0x1f, 0x90,
	0x10, 0xdb, 0x38, 0xc4, 0x15, 0x69, 0x5d, 0xba, 0x56, 0xdc, 0x7c, 0x4f, 0x9b, 0x12, 0x59, 0x6b,
	0x1e, 0x3f, 0x25, 0xdd, 0xf0, 0x90, 0x9b, 0x5b, 0x63, 0x47, 0xb4, 0x0d, 0xd9, 0xc0, 0x23, 0xdd,
	0x8a, 0xcc, 0x02, 0xbc, 0x33, 0x35, 0x40, 0xbc, 0x6a, 0xdb, 0x23, 0x5d, 0x8b, 0xb9, 0xa0, 0xcf,
	0x21, 0x17, 0x84, 0x38, 0x1c, 0x05, 0x95, 0xcc, 0x8c, 0xd5, 0xc7, 0xce, 0xcc, 0xdc, 0xe2, 0x6e,
	0xea, 0xaf, 0x32, 0xac, 0x8a, 0x71, 0xd1, 0x15, 0x00, 0xec, 0x39, 0xf7, 0x88, 0x4f, 0xa3, 0xb0,
	0x3d, 0x15, 0x2c, 0x61, 0x06, 0xed, 0x82, 0x12, 0xe2, 0xe0, 0x34, 0xa8, 0xc8, 0xeb, 0x99, 0x6b,
	0xc5, 0xcd, 0x0f, 0xe7, 0xca, 0x56, 0xeb, 0x50, 0x17, 0xc3, 0x0d, 0xfd, 0x33, 0x2b, 0x72, 0xa7,
	0xeb, 0x0c, 0x47, 0xa1, 0x37, 0x0a, 0xe9, 0x2b, 0x96, 0x7d, 0xc1, 0x12, 0x66, 0xd0, 0x3a, 0x14,
	0x6d, 0x12, 0x74, 0x7d, 0xc7, 0x0b, 0x69, 0x22, 0x59, 0x66, 0x20, 0x4e, 0xa1, 0x0a, 0xac, 0xf4,
	0x86, 0x7e, 0x97, 0x98, 0x76, 0x45, 0x61, 0x6f, 0xe3, 0x21, 0x42, 0x90, 0x75, 0xf1, 0x80, 0x54,
	0x72, 0x6c, 0x9a, 0x3d, 0xa3, 0x2a, 0xe4, 0x1d, 0x37, 0x24, 0xbe, 0x8b, 0xfb, 0x95, 0x95, 0x75,
	0xe9, 0x5a, 0xde, 0x1a, 0x8f, 0xab, 0x5f, 0x02, 0x24, 0x09, 0xa2, 0x32, 0x64, 0x4e, 0xc9, 0x19,
	0xdf, 0x3a, 0x7d, 0x44, 0xb7, 0x41, 0x79, 0x86, 0xfb, 0x23, 0xc2, 0x2b, 0x74, 0x75, 0xea, 0x9e,
	0x69, 0x14, 0x56, 0x9d, 0xc8, 0xfe, 0x13, 0x79, 0x4b, 0x52, 0xbf, 0xcb, 0x40, 0x29, 0x0d, 0x3e,
	0xda, 0x1d, 0x57, 0x8d, 0x2e, 0x52, 0xda, 0xd4, 0xe6, 0xac, 0x9a, 0x96, 0x2e, 0x1e, 0xda, 0x82,
	0xc2, 0xc8, 0xb3, 0x71, 0x48, 0xec, 0x5a, 0xc8, 0x73, 0xab, 0x6a, 0x11, 0x7f, 0xb5, 0x98, 0xbf,
	0x5a, 0x27, 0xe6, 0xaf, 0x95, 0x18, 0xa3, 0xbb, 0x71, 0x15, 0x33, 0xac, 0x8a, 0x9b, 0xf3, 0x26,
	0xf0, 0x62, 0x1d, 0x6f, 0x81, 0x42, 0x7c, 0x7f, 0xe8, 0xb3, 0x0a, 0x15, 0x37, 0xaf, 0x4c, 0x8d,
	0x64, 0x50, 0x2b, 0x2b, 0x32, 0xae, 0x3e, 0x9a, 0x81, 0xf8, 0x76, 0x1a, 0xf1, 0xb7, 0x2e, 0x46,
	0x3c, 0x42, 0x45, 0xc0, 0x7c, 0x1b, 0x72, 0x1c, 0xea, 0x22, 0xac, 0xb4, 0x8c, 0x86, 0x6e, 0x36,
	0xf6, 0xca, 0x97, 0x50, 0x01, 0x14, 0xcb, 0xa8, 0xe9, 0x0f, 0xca, 0x32, 0x02, 0xc8, 0xed, 0xd6,
	0xcc, 0x03, 0x43, 0x2f, 0x67, 0xa8, 0x8d, 0x6e, 0x1c, 0x18, 0x1d, 0x43, 0x2f, 0x67, 0xd5, 0xdf,
	0x25, 0x40, 0xf1, 0xa6, 0x4d, 0xf7, 0xd9, 0xb0, 0x8b, 0x19, 0xd9, 0x96, 0xd2, 0xe8, 0xf5, 0x54,
	0xa3, 0x6f, 0xcc, 0x04, 0x3d, 0x59, 0x5f, 0x68, 0x79, 0x73, 0xa2, 0xe5, 0x6f, 0x2c, 0x12, 0x26,
	0xdd, 0xfc, 0x5f, 0xcb, 0x70, 0xf9, 0xfc, 0xb5, 0x68, 0x7b, 0xc6, 0xe1, 0x4c, 0x3b, 0x96, 0x81,
	0x64, 0x06, 0xb5, 0x21, 0xe7, 0xb8, 0xde, 0x28, 0x8c, 0x75, 0x60, 0x67, 0xc1, 0xcd, 0x68, 0x26,
	0xf3, 0x8e, 0xa8, 0xc4, 0x43, 0xd1, 0x1e, 0xf5, 0xb0, 0x4f, 0xdc, 0xd0, 0xb4, 0xb9, 0x22, 0x8c,
	0xc7, 0xd5, 0xc7, 0x50, 0x14, 0x5c, 0xfe, 0x11, 0x65, 0xce, 0x3c, 0x62, 0xdf, 0xa3, 0xa6, 0x22,
	0x65, 0xfe, 0x52, 0xa0, 0x32, 0x0d, 0x30, 0xd4, 0x9a, 0x68, 0xd8, 0xad, 0x85, 0x31, 0x5f, 0x5e,
	0xeb, 0x5a, 0xe9, 0xd6, 0xfd, 0x74, 0xf1, 0x54, 0x5e, 0x6c, 0xe2, 0x1d, 0xc8, 0x45, 0xd2, 0xcb,
	0xbb, 0x78, 0x2e, 0xf0, 0xb8, 0x0b, 0x3a, 0x81, 0x55, 0xfb, 0xcc, 0xc5, 0x03, 0xa7, 0xcb, 0x02,
	0x57, 0x14, 0x96, 0x57, 0x7d, 0xf1, 0xbc, 0x74, 0x21, 0x4a, 0x94, 0x5e, 0x2a, 0x70, 0x22, 0x35,
	0xb9, 0x45, 0xa4, 0xe6, 0xe1, 0x0c, 0xa9, 0xf9, 0x38, 0xcd, 0x9b, 0xf5, 0x0b, 0xa5, 0xc6, 0x1a,
	0xb9, 0x02, 0x69, 0xaa, 0x8f, 0xe1, 0xbf, 0x2f, 0x24, 0x7d, 0xce, 0x12, 0x37, 0xd3, 0x4b, 0xbc,
	0x71, 0xf1, 0x12, 0x02, 0x29, 0x1f, 0x89, 0x3a, 0x76, 0xd4, 0xd8, 0x6f, 0x34, 0xef, 0x37, 0xca,
	0x97, 0xd0, 0x1a, 0x14, 0xda, 0xf5, 0xbb, 0x86, 0x7e, 0x44, 0xf5, 0x4b, 0x42, 0xff, 0x81, 0xa2,
	0xd9, 0x78, 0xd2, 0xb2, 0x9a, 0x7b, 0x96, 0xd1, 0x6e, 0x97, 0x65, 0xf6, 0xfe, 0xa8, 0x5e, 0x37,
	0x0c, 0x9d, 0xe9, 0x5b, 0xa2, 0x75, 0x59, 0x1a, 0xa7, 0x76, 0xa7, 0x69, 0x51, 0xad, 0x53, 0xd4,
	0x3f, 0x24, 0x28, 0xeb, 0xc4, 0x23, 0xae, 0x4d, 0xdc, 0xee, 0x59, 0x7d, 0xe8, 0xf6, 0x9c, 0x13,
	0xd4, 0x86, 0xbc, 0x4f, 0xbe, 0x1a, 0x39, 0x3e, 0xa1, 0x6c, 0xa7, 0xa5, 0xbc, 0x3d, 0x35, 0xdf,
	0x49, 0x67, 0xcd, 0xe2, 0x9e, 0x51, 0xf9, 0xc6, 0x81, 0xd0, 0xff, 0x40, 0xc1, 0xcf, 0xb1, 0x13,
	0x51, 0x5d, 0xb1, 0xa2, 0x41, 0xd5, 0x85, 0xb5, 0x94, 0xc3, 0x39, 0xd0, 0xed, 0xa5, 0xa1, 0xbb,
	0x71, 0x21, 0x74, 0x49, 0x3a, 0x2d, 0xec, 0xe3, 0x01, 0x09, 0x89, 0x9f, 0x3a, 0x16, 0x7e, 0x94,
	0x20, 0xcb, 0x2e, 0x17, 0x4b, 0x51, 0xf3, 0x8f, 0x52, 0x6a, 0x3e, 0xc7, 0xa5, 0x20, 0xd2, 0xef,
	0x9d, 0x09, 0xfd, 0x9e, 0xeb, 0x6c, 0x8b, 0x15, 0xfb, 0xb7, 0x0c, 0xe4, 0xe3, 0x78, 0xf4, 0x8a,
	0xd4, 0x1b, 0xb9, 0x5d, 0xda, 0x41, 0x16, 0xe9, 0x71, 0xd4, 0xc4, 0x29, 0x64, 0x4c, 0xa8, 0xf4,
	0xf5, 0x99, 0x49, 0x9e, 0xab, 0xcb, 0xfb, 0x02, 0x25, 0x22, 0xd5, 0xd9, 0x98, 0x1d, 0x68, 0x26,
	0x15, 0xb2, 0x02, 0x15, 0x04, 0x05, 0x52, 0x16, 0x56, 0xa0, 0x57, 0x7d, 0x36, 0xfc, 0xeb, 0x3c,
	0xfd, 0x46, 0x8e, 0x34, 0x8b, 0xf7, 0xfe, 0x9d, 0x89, 0xd3, 0xe7, 0xfd, 0x39, 0x18, 0xb3, 0xbc,
	0xf3, 0xe6, 0x16, 0x28, 0x3d, 0xc6, 0xaf, 0xcc, 0x0c, 0xd5, 0xdd, 0xa5, 0x56, 0x56, 0x64, 0xfc,
	0x72, 0xd7, 0x42, 0xf5, 0x03, 0x51, 0xef, 0xda, 0x9d, 0x1a, 0xd3, 0x29, 0xe1, 0xde, 0x26, 0x09,
	0x5a, 0x26, 0xab, 0x3f, 0x49, 0x50, 0x99, 0x06, 0x27, 0xea, 0x40, 0x96, 0x2e, 0xc0, 0x21, 0xfb,
	0x62, 0xe1, 0x7a, 0x08, 0xda, 0x46, 0x49, 0x61, 0xb1, 0x68, 0x8c, 0xbc, 0x7d, 0x07, 0x07, 0x0c,
	0xc2, 0x82, 0x15, 0x0d, 0xd4, 0x1d, 0x28, 0xa5, 0xad, 0x51, 0x1e, 0xb2, 0x7a, 0xad, 0x53, 0x2b,
	0x5f, 0xa2, 0x1b, 0xa9, 0x37, 0x1b, 0x1d, 0xab, 0x79, 0x50, 0x96, 0x10, 0x82, 0x92, 0xfe, 0xa0,
	0x51, 0x3b, 0x34, 0xeb, 0x4f, 0x9a, 0x47, 0x9d, 0xd6, 0x51, 0xa7, 0x2c, 0xab, 0x3f, 0x4b, 0xb0,
	0xc2, 0x8f, 0x96, 0xe5, 0xe8, 0xd2, 0x56, 0x4a, 0x97, 0xde, 0x9e, 0x75, 0x9e, 0x09, 0xd2, 0xf4,
	0xd9, 0x84, 0x34, 0xbd, 0x3b, 0xd3, 0x37, 0xad, 0x4e, 0xdf, 0xca, 0x50, 0x14, 0xa2, 0x26, 0xd4,
	0x91, 0x16, 0xa1, 0xce, 0x65, 0xc8, 0xd1, 0x5b, 0x89, 0x69, 0x73, 0x90, 0xf9, 0x08, 0xdd, 0x1d,
	0x8b, 0x59, 0x66, 0xc6, 0xa7, 0xa7, 0x90, 0xc3, 0xb9, 0x7a, 0xa6, 0xc2, 0xaa, 0x33, 0xbe, 0x7c,
	0x98, 0x36, 0xff, 0xb8, 0x4c, 0xcd, 0xbd, 0xf2, 0xfb, 0xe6, 0x9f, 0x32, 0xac, 0xa5, 0x50, 0xa4,
	0x62, 0x9d, 0x6a, 0xf3, 0xeb, 0xf3, 0xa1, 0xbf, 0xbc, 0x4e, 0x4f, 0x34, 0x38, 0xb3, 0xf8, 0x2d,
	0xf0, 0xe5, 0x1a, 0xfe, 0xe9, 0x2b, 0xbd, 0xe0, 0x30, 0x15, 0xd9, 0x37, 0x5b, 0x2d, 0x43, 0x2f,
	0xe7, 0xd4, 0x87, 0x50, 0x4a, 0xf7, 0x0c, 0x2a, 0x81, 0xec, 0xc4, 0x1f, 0x37, 0xb2, 0x63, 0x53,
	0xe8, 0xba, 0x3e, 0xe1, 0xd0, 0x65, 0x66, 0x43, 0x37, 0x36, 0x56, 0x7f, 0x90, 0x00, 0x12, 0x50,
	0x10, 0x12, 0xc4, 0xa7, 0x90, 0x48, 0x47, 0xc2, 0x97, 0x55, 0x4e, 0x05, 0xb4, 0x07, 0xb9, 0x3e,
	0x3e, 0x26, 0xfd, 0x39, 0x0e, 0xd6, 0x71, 0x78, 0xed, 0x80, 0x79, 0x70, 0x4e, 0x47, 0xee, 0xd5,
	0x6d, 0x28, 0x0a, 0xd3, 0xe7, 0xf0, 0x35, 0xb5, 0x7e, 0x41, 0xa4, 0xe2, 0x55, 0x50, 0x58, 0x51,
	0x50, 0x05, 0x56, 0x06, 0x24, 0x08, 0xf0, 0x49, 0x6c, 0x14, 0x0f, 0xd5, 0x26, 0x28, 0xac, 0x47,
	0xa9, 0x89, 0x3f, 0x72, 0x43, 0x67, 0x30, 0x36, 0xe1, 0x43, 0xf4, 0x3a, 0x14, 0x5c, 0x3c, 0x20,
	0x81, 0x87, 0xbb, 0x84, 0x7f, 0xbd, 0x25, 0x13, 0x14, 0x6a, 0x53, 0xe7, 0x8d, 0x26, 0x9b, 0xba,
	0xfa, 0xbd, 0x04, 0x6b, 0xc9, 0x8e, 0x0e, 0xb1, 0x47, 0x4f, 0x50, 0xf6, 0xcc, 0x2f, 0x9d, 0x37,
	0xe6, 0x00, 0xe2, 0x10, 0x7b, 0x1a, 0x7b, 0xe0, 0x1f, 0x33, 0xec, 0xb9, 0xfa, 0x08, 0x20, 0x99,
	0x5c, 0x7e, 0xe3, 0xee, 0x43, 0x29, 0x79, 0x71, 0xe0, 0x04, 0x21, 0x0d, 0x28, 0x66, 0x3e, 0x5f,
	0x40, 0xf6, 0x77, 0x67, 0xe5, 0xa1, 0xc2, 0x5e, 0x1d, 0xe7, 0x18, 0xbf, 0x6e, 0xfe, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x36, 0x37, 0x89, 0xaf, 0x14, 0x00, 0x00,
}
